[locust run]
host: http://newtours.demoaut.com
locustfile: /mnt/locust/basics/basics_locust_01_read_from_config_docker.py

[headless mode]
headless: true
users:5
hatch-rate: 1
run-time: 20s

# if we need run in UI mode, then we need to comment out the code below headless mode

# Terminal -> locust --config=/Users/dipanjankundu/Personal_Project/PycharmProjects/locustProject/config/locust.yml