[locust run]
host: http://newtours.demoaut.com
locustfile: basics/basic_locust_01_logging.py

[headless mode]
headless: true
users:5
hatch-rate: 1
run-time: 20s

# if we need run in UI mode, then we need to comment out the code below headless mode

# Terminal -> locust --config=/Users/dipanjankundu/My\ Personal\ Projects/PycharmProjects/locustProject/config/locust.yml