#For configuring locust script
[locust script]
locustfile: basics/basic_locust_01_master_slave.py
host: http://newtours.demoaut.com

#For configuring worker mode
[locust worker mode]
worker: true
master-host: 127.0.0.1
# master-host: public_ip_address of the master machine [if its not in the same machine/local host]
master-port: 5557


[locust headless]
#headless: true
#users:5
#hatch-rate: 1
#run-time: 20s

# Terminal -> locust --config=/Users/dipanjankundu/Personal_Project/PycharmProjects/locustProject/config/worker.yml






